# Generated by Django 6.0 on 2026-04-27 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('owner_avatar', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=60)),
                ('stars', models.IntegerField(default=0)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='repositorios.repometa')),
            ],
            options={
                'unique_together': {('user', 'repo')},
            },
        ),
        migrations.CreateModel(
            name='SavedRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='repositorios.repometa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'repo')},
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='repositorios.repometa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'repo')},
            },
        ),
    ]
